### ISSUE TITLE
onPieceClicked event

### ISSUE THREAD

**Issue by chitoiur** [oakmac/chessboardjs#100] opened 2015-05-28 16:44 UTC
It would be useful if there was an event for when a piece is clicked. Are there any plans to add this?

**Comment by oakmac** [comment] 2015-06-01 01:49
Is there a use case that isn't covered by [onDragStart](http://chessboardjs.com/docs#config:onDragStart) and [onDrop](http://chessboardjs.com/docs#config:onDrop)?

**Comment by chitoiur** [comment] 2015-06-01 03:04
I may have mis-titled my request. I meant more along the lines of clicking on a piece and “selecting” it. Then firing off an event. Then, the user can click on an allowed square and move the piece there (instead of drag and rope (like on chess.com).



From: Chris Oakman
Sent: ‎Sunday‎, ‎May‎ ‎31‎, ‎2015 ‎9‎:‎49‎ ‎PM
To: oakmac/chessboardjs
Cc: Robert Chitoiu





Is there a use case that isn't covered by onDragStart and onDrop?

**Comment by oakmac** [comment] 2015-06-01 03:10
Sounds like a duplicate of Issue #34

**Comment by chitoiur** [comment] 2015-06-01 04:11
Indeed… sorry about that. Apparently I did not look carefully enough bore opening.



From: Chris Oakman
Sent: ‎Sunday‎, ‎May‎ ‎31‎, ‎2015 ‎11‎:‎10‎ ‎PM
To: oakmac/chessboardjs
Cc: Robert Chitoiu





Sounds like a duplicate of Issue #34

**Comment by oakmac** [comment] 2015-06-01 04:12
No worries; I appreciate the report :)

**Closed by oakmac** 2015-06-01 04:12 UTC
